services:
  dsa-landing:
    build:
      context: ./deploy_packages/site-dsa
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsa-landing.rule=Host(`dsa.berocket.com.br`)"
      - "traefik.http.routers.dsa-landing.entrypoints=http"
      - "traefik.http.services.dsa-landing.loadbalancer.server.port=80"
    restart: always

  drumwave-landing:
    build:
      context: ./deploy_packages/site-dw-ai
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drumwave-landing.rule=Host(`drumwave.berocket.com.br`)"
      - "traefik.http.routers.drumwave-landing.entrypoints=http"
      - "traefik.http.services.drumwave-landing.loadbalancer.server.port=80"
    restart: always

  idr-landing:
    build:
      context: ./deploy_packages/site-idr
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idr-landing.rule=Host(`idrs.berocket.com.br`)"
      - "traefik.http.routers.idr-landing.entrypoints=http"
      - "traefik.http.services.idr-landing.loadbalancer.server.port=80"
    restart: always
