services:
  dsa-landing:
    build:
      context: ./deploy_packages/site-dsa
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsa-landing.rule=Host(`dsa.berocket.com.br`)"
      - "traefik.http.routers.dsa-landing.entrypoints=http"
      - "traefik.http.services.dsa-landing.loadbalancer.server.port=80"
    restart: always



  idr-landing:
    build:
      context: ./deploy_packages/site-idr
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idr-landing-http.rule=Host(`idrs.berocket.com.br`)"
      - "traefik.http.routers.idr-landing-http.entrypoints=http"
      - "traefik.http.routers.idr-landing-http.middlewares=redirect-to-https"
      - "traefik.http.routers.idr-landing-https.rule=Host(`idrs.berocket.com.br`)"
      - "traefik.http.routers.idr-landing-https.entrypoints=https"
      - "traefik.http.routers.idr-landing-https.tls=true"
      - "traefik.http.routers.idr-landing-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.idr-landing.loadbalancer.server.port=80"
    restart: always

  data-savings-landing:
    build:
      context: ./deploy_packages/site-data-savings
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.data-savings-landing-http.rule=Host(`data-savings.berocket.com.br`)"
      - "traefik.http.routers.data-savings-landing-http.entrypoints=http"
      - "traefik.http.routers.data-savings-landing-http.middlewares=redirect-to-https"
      - "traefik.http.routers.data-savings-landing-https.rule=Host(`data-savings.berocket.com.br`)"
      - "traefik.http.routers.data-savings-landing-https.entrypoints=https"
      - "traefik.http.routers.data-savings-landing-https.tls=true"
      - "traefik.http.routers.data-savings-landing-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.data-savings-landing.loadbalancer.server.port=80"
    restart: always
