events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name dw.berocket.com.br localhost;
        location / {
            root   /usr/share/nginx/html/drumwave;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
        location /Docs/ {
            alias /usr/share/nginx/html/Docs/;
            add_header Content-Disposition "inline";
        }
    }

    server {
        listen 80;
        server_name idrs.berocket.com.br;
        location / {
            root   /usr/share/nginx/html/idr-website;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
        location /Docs/ {
            alias /usr/share/nginx/html/Docs/;
            add_header Content-Disposition "inline";
        }
    }

    server {
        listen 80;
        server_name data-savings.berocket.com.br;
        location / {
            root   /usr/share/nginx/html/data-savings;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
        location /docs/ {
            alias /usr/share/nginx/html/docs/;
            add_header Content-Disposition "inline";
        }
    }

    server {
        listen 80;
        server_name dsa.berocket.com.br;
        location / {
            root   /usr/share/nginx/html/dsa;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
        location /docs/ {
            alias /usr/share/nginx/html/docs/;
            add_header Content-Disposition "inline";
        }
    }

    server {
        listen 80;
        server_name idrs2.berocket.com.br;
        location / {
            root   /usr/share/nginx/html/idr2-website;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
